service: stores-api

plugins:
  - serverless-offline
  - serverless-domain-manager

custom:
  allowedHeaders:
    - Accept
    - Content-Type
    - Content-Length
    - Authorization
    - X-Amz-Date
    - X-Api-Key
    - X-Amz-Security-Token
    - X-Amz-User-Agent
  stage: ${opt:stage, self:provider.stage}
  domains:
    prod: stores.buyontrust.com
    dev: dev-stores.buyontrust.com
  customDomain:
    basePath: ""
    domainName: ${self:custom.domains.${self:custom.stage}}
    stage: "${self:custom.stage}"
    certificateName: buyontrust.com
    createRoute53Record: true

provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  profile: buyontrust
  region: us-east-1
  memorySize: 128
  timeout: 5
  endpointType: regional

functions:
  storesByZip:
    handler: api/storesByZip.handler
    description: GET list of by proximity
    events:
      - http:
          path: /{zip}
          method: get
          cors: 
            origin: '*'
            headers: ${self:custom.allowedHeaders}

